# -*- coding: utf-8 -*-
"""Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zHyWfiq0YWaJIy99gbqPi2u7mTMya-Y
"""

from math import sqrt

def print_primes(a, b):
  for x in range(a, b + 1):
    if(is_prime(x)):
      print(x)

# тривиальный тест простоты
def is_prime(N):
  i = 2
  while i <= sqrt(N):
    if N % i == 0:
        return False
    i += 1
  return True

n = 433
m = 399
#print_primes(2, n)
#print_primes(m, n)


def Euclid(a, b):
   while b != 0:
        a, b = b, a % b
   return a


def gcd_three_numbers(a, b, c):
    return Euclid(Euclid(a, b), c)

gcd_three_numbers(48, 120, 64)