-------------------------------------------------------------—Œ«ƒ¿Õ»≈ “¿¡À»÷-------------------------------------------------------------------------------------------
alter session set container = MusicShop

--GENERATED BY DEFAULT AS IDENTITY (START WITH 1) 
CREATE TABLE Categories (
    CategoryID INT PRIMARY KEY,
    CategoryName NVARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE Manufacturers (
    ManufacturerID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    ManufacturerName NVARCHAR2(50) NOT NULL UNIQUE,
    Country NVARCHAR2(50)
);


CREATE TABLE Instruments (
    InstrumentID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    InstrumentName VARCHAR(50) NOT NULL, --¡€ÀŒ NVARCHAR2
    CategoryID INT REFERENCES Categories(CategoryID) ON DELETE CASCADE,
    ManufacturerID INT REFERENCES Manufacturers(ManufacturerID) ON DELETE CASCADE,
    Availability NUMBER(1, 0) NOT NULL CHECK (Availability IN (0, 1)),
    Cost NUMBER(10, 2) NOT NULL CHECK (Cost > 0)
);

CREATE TABLE Users (
    UserID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    UserName NVARCHAR2(50) NOT NULL,
    Balance NUMBER(10, 2) NOT NULL CHECK (Balance >= 0)
);

CREATE TABLE Orders (
    OrderID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    ReservationDate DATE NOT NULL
);


CREATE TABLE OrderItems (
    OrderItemID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    OrderID INT REFERENCES Orders(OrderID) ON DELETE CASCADE,
    InstrumentID INT REFERENCES Instruments(InstrumentID) ON DELETE CASCADE
);

CREATE TABLE InstrumentsReview (
    ReviewID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    InstrumentID INT REFERENCES Instruments(InstrumentID) ON DELETE CASCADE,
    ReviewText NVARCHAR2(1000) NOT NULL
);



-------------------------------------------------------------”ƒ¿À≈Õ»≈ “¿¡À»÷-------------------------------------------------------------------------------------------
    DROP TABLE InstrumentsReview;
    DROP TABLE OrderItems;
    DROP TABLE Orders;
    DROP TABLE Instruments;
    DROP TABLE Categories;
    DROP TABLE Manufacturers;
    DROP TABLE Users;

-------------------------------------------------------------¬—“¿¬ ¿ ƒ¿ÕÕ€’-------------------------------------------------------------------------------------------
------------------------------------------------------Categories--------------------------------------------------
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (1, 'Strings');
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (2, 'Brass');
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (3, 'Reed');
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (4, 'Drums');
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (5, 'Keyboards');
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (6, 'Mechanical');
    INSERT INTO Categories (CategoryID,CategoryName) VALUES (7, 'Electromusical');
    
    DELETE FROM CATEGORIES
    SELECT * FROM Categories
    
---------------------------------------------------Manufactures-----------------------------------------------------
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Cort', 'South Korea');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Taylor', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Crafter', 'South Korea');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Yamaha', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Fender', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Gibson', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Ibanez', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Martin', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Epiphone', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Rickenbacker', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('PRS', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Jackson', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Schecter', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('ESP', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Gretsch', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Guild', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Squier', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('BC Rich', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Music Man', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Washburn', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Steinway & Sons', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Kawai', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Roland', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Korg', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Moog', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Behringer', 'Germany');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('B?sendorfer', 'Austria');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Casio', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Charvel', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Danelectro', 'United States');
    
    DELETE FROM Manufacturers
    SELECT * FROM Manufacturers
    
---------------------------------------------------------------Instruments---------------------------------------------------

    DELETE FROM Instruments
    SELECT count(*) FROM Instruments
    SELECT * FROM Instruments order by InstrumentID



---------------------------------------------------------------Users---------------------------------------------------
    INSERT INTO Users (UserName, Balance) VALUES ('John Doe', 1000.68);
    INSERT INTO Users (UserName, Balance) VALUES ('Anna Bell', 1200.54);
    
    
    DELETE FROM Users
    SELECT * FROM Users
    
    
---------------------------------------------------------------Reviews---------------------------------------------------
    --¬ÒÚ‡‚Í‡ ‰‡ÌÌ˚ı ‚ Ú‡·ÎËˆÛ InstrumentsReview
    INSERT INTO InstrumentsReview (UserID, InstrumentID, ReviewText) VALUES (1, 1, 'Great guitar, love the sound!');
    INSERT INTO InstrumentsReview (UserID, InstrumentID, ReviewText) VALUES (1, 2, 'Awesome piano, excellent build quality.');

    
    DELETE FROM InstrumentsReview
    SELECT * FROM InstrumentsReview
    

    SELECT *
    FROM Instruments i
    JOIN InstrumentsReview ir ON i.InstrumentID = ir.InstrumentID;


