-------------------------------------------------------------СОЗДАНИЕ ТАБЛИЦ-------------------------------------------------------------------------------------------
CREATE TABLE Categories (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CategoryName NVARCHAR2(50) NOT NULL UNIQUE
);


CREATE TABLE Manufacturers (
    ManufacturerID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    ManufacturerName NVARCHAR2(50) NOT NULL UNIQUE,
    Country NVARCHAR2(50)
);


CREATE TABLE Instruments (
    InstrumentID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    InstrumentName NVARCHAR2(50) NOT NULL,
    CategoryID NUMBER REFERENCES Categories(CategoryID) ON DELETE CASCADE,
    ManufacturerID NUMBER REFERENCES Manufacturers(ManufacturerID) ON DELETE CASCADE,
    Availability NUMBER(1, 0) NOT NULL CHECK (Availability IN (0, 1)),
    Cost FLOAT NOT NULL CHECK (Cost > 0)
);


CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    InstrumentID NUMBER REFERENCES Instruments(InstrumentID) ON DELETE CASCADE,
    ReservationDate DATE NOT NULL 
);

CREATE TABLE InstrumentsReview (
    ReviewID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    InstrumentID NUMBER REFERENCES Instruments(InstrumentID) ON DELETE CASCADE,
    ReviewText NVARCHAR2(1000) NOT NULL
);


-------------------------------------------------------------УДАЛЕНИЕ ТАБЛИЦ-------------------------------------------------------------------------------------------
    DROP TABLE Orders;
    DROP TABLE Instruments;
    DROP TABLE Categories;
    DROP TABLE Manufacturers;
    DROP TABLE InstrumentsReview;


-------------------------------------------------------------ВСТАВКА ДАННЫХ-------------------------------------------------------------------------------------------
------------------------------------------------------Categories--------------------------------------------------
    INSERT INTO Categories (CategoryName) VALUES ('Strings');
    INSERT INTO Categories (CategoryName) VALUES ('Brass');
    INSERT INTO Categories (CategoryName) VALUES ('Reed');
    INSERT INTO Categories (CategoryName) VALUES ('Drums');
    INSERT INTO Categories (CategoryName) VALUES ('Keyboards');
    INSERT INTO Categories (CategoryName) VALUES ('Mechanical');
    INSERT INTO Categories (CategoryName) VALUES ('Electromusical');
    
    TRUNCATE TABLE CATEGORIES
    SELECT * FROM Categories
    
---------------------------------------------------Manufactures-----------------------------------------------------
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Cort', 'South Korea');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Taylor', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Crafter', 'South Korea');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Yamaha', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Fender', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Gibson', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Ibanez', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Martin', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Epiphone', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Rickenbacker', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('PRS', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Jackson', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Schecter', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('ESP', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Gretsch', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Guild', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Squier', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('BC Rich', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Music Man', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Washburn', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Steinway & Sons', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Kawai', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Roland', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Korg', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Moog', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Behringer', 'Germany');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('B?sendorfer', 'Austria');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Casio', 'Japan');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Charvel', 'United States');
    INSERT INTO Manufacturers (ManufacturerName, Country) VALUES ('Danelectro', 'United States');
    
    TRUNCATE TABLE Manufacturers
    SELECT * FROM Manufacturers
    
---------------------------------------------------------------Instruments---------------------------------------------------
    --Вставка инструментов Reed
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Yamaha YCL-255', 3, 4, 1, 1000.00);
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Selmer Paris Reference 54', 3, 6, 1, 5000.00);
    
    --Вставка инструментов Drums
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Pearl Export Series', 4, 26, 1, 800.00);
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Mapex Saturn V', 4, 27, 1, 1200.00);
    
    --Вставка инструментов Keyboards
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Kawai MP11', 5, 22, 1, 2500.00);
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Roland Juno-DS88', 5, 23, 1, 1200.00);
    
    --Вставка инструментов Mechanical
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Steinway Model D', 6, 21, 1, 50000.00);
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('B?sendorfer Imperial', 6, 28, 1, 70000.00);
    
    --Вставка инструментов Electromusical (продолжение)
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Casio PX-870', 7, 29, 1, 900.00);
    INSERT INTO Instruments (InstrumentName, CategoryID, ManufacturerID, Availability, Cost) VALUES ('Behringer DeepMind 12', 7, 30, 1, 800.00);


    TRUNCATE TABLE Instruments
    SELECT * FROM Instruments


---------------------------------------------------------------Reviews---------------------------------------------------
    --Вставка данных в таблицу InstrumentsReview
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (1, 'Отличный инструмент, звучание на высоте!');
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (1, 'Отличный инструмент, звучание на высоте!');
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (2, 'Прекрасная гитара, удивительные детали!');
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (4, 'Барабаны звучат потрясающе, очень доволен!');
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (5, 'Клавишный инструмент с потрясающей функциональностью.');
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (6, 'Фортепиано Steinway - лучший выбор для профессионала.');
    INSERT INTO InstrumentsReview (InstrumentID, ReviewText) VALUES (7, 'Отличный синтезатор с широким звуковым спектром.');

    TRUNCATE TABLE InstrumentsReview

    SELECT *
    FROM Instruments i
    JOIN InstrumentsReview ir ON i.InstrumentID = ir.InstrumentID;

