package com.getinfo.error;

public enum ErrorKey {
    EMPTY_PASSWORD,
    EMPTY_USERNAME,
    EMPTY_PARAMETERS,
    EMPTY_PARAM_KEY,
    EMPTY_PARAM_VALUE,
    INVALID_CLIENTID,
    EMPTY_SERVICEID,
    INSUFFICIENT_PARAMETERS,
    NO_CLIENT_ID,
    MULTIPLE_CLIENT_IDS,

    NON_UNIQUE_CLIENT_ID
}
